version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Shb316381649
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: bash -c "python init_db.py && flask run --host=0.0.0.0"
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:Shb316381649@db:5432/mydatabase
    depends_on:
      - db

volumes:
  postgres_data:
